site_name: Protein Annotator
site_url: https://example.com/

repo_name: BioinformaticaUNQ/protein_annotator
repo_url: https://github.com/BioinformaticaUNQ/protein_annotator

nav:
  - Home: index.md
  - About: about.md

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - python
    - yaml
